#!/bin/sh
#
# (c) GMD Karlsruhe

LIST=/tmp/$1.$$
SRC=$1
ERROR=$2

trap "rm -f $LIST; exit 5" 3
$MOCKA/sys/Lister $SRC $ERROR $LIST
vi +'map v j/^@[ ]*^/\^k|1' $LIST < /dev/tty; 
$MOCKA/sys/Unlister $SRC $LIST
rm -f $LIST $ERROR
