#!/bin/sh
#
# Christian Maurer   v. 14. August 2006

mkdir -p m2bin

export MOCKAM2=
export MOCKALINK=

for m in SysLib Exceptions LREAL libc miscc
  do m2 -s $m
done

m2 -c SysLib

/usr/bin/as -o m2bin/Exceptions.o Exceptions.s

for m in LREAL libc miscc
  do gcc -c -o m2bin/$m.o $m.c
done

echo p tst | m2

tst
