#!/bin/sh

LIST=/tmp/$1.$$
SRC=$1
ERROR=$2

trap "rm -f $LIST; exit 5" 3
$MOCKADIR/sys/lister $SRC $ERROR $LIST
vi +'map v j/^@[ ]*^/\^k|1' $LIST < /dev/tty; 
$MOCKADIR/sys/unlister $SRC $LIST
rm -f $LIST $ERROR
