#!/bin/sh
#
# Christian Maurer   v. 14. August 2006

export MOCKA=/home/gunter/SANDBOX/Mocka_m2_0608m

mkdir -p m2bin

export MOCKAM2=
export MOCKALINK=

echo p Mc | $MOCKA/sys/m2

mv Mc $MOCKA/sys

rm -rf m2bin
