Don't even try to build this ;)

Everything here is a hack but I don't have a better solution since 
the upstream source is wicked. The backend-generator is not available
in a working binary format and even less in source.

The orig.tar.gz was created by untarring both the source and the binary 
distribution and tarring the result up (with a renamed root directory).
In fact some of the files from the binary distribution are not needed 
for building the package but I lack the motivation to sort that out now.

 -- Torsten Landschoff <torsten@debian.org>  Sat, 23 Oct 1999 20:44:08 +0200
